import Link from "next/link";

export default function HomePage() {
  return <main className="min-h-screen bg-[#f5f2eb] text-stone-900">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><Link className="text-lg font-semibold tracking-tight" href="/">Salon SaaS</Link><nav className="flex items-center gap-3"><Link className="text-sm font-semibold text-stone-700" href="#planes">Planes</Link><Link className="btn-secondary !py-2" href="/login">Ingresar</Link></nav></header>
    <section className="mx-auto grid max-w-6xl gap-10 px-6 pb-20 pt-16 lg:grid-cols-[1.1fr_0.9fr] lg:pt-28"><div><p className="label text-teal-700">Gestión para salones</p><h1 className="mt-4 max-w-3xl text-5xl font-semibold tracking-[-0.04em] sm:text-6xl">Agenda, ventas e inventario en un solo lugar.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-stone-600">Ordena las citas, cobra anticipos, controla stock y revisa lo importante del negocio sin planillas dispersas.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" href="/registro">Crear mi salón</Link><Link className="btn-secondary" href="/login">Ya tengo cuenta</Link></div></div><div className="rounded-[2rem] bg-stone-900 p-7 text-stone-100 shadow-xl"><p className="text-sm font-semibold text-teal-300">Hoy en tu salón</p><div className="mt-8 grid gap-4"><div className="rounded-2xl bg-white/10 p-4"><p className="text-sm text-stone-300">Próxima cita</p><p className="mt-1 text-xl font-semibold">Agenda ordenada por profesional</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-sm text-stone-300">Cobros</p><p className="mt-1 text-xl font-semibold">Anticipos y saldos visibles</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-sm text-stone-300">Inventario</p><p className="mt-1 text-xl font-semibold">Stock por sucursal</p></div></div></div></section>
    <section className="border-y border-stone-200 bg-white/60"><div className="mx-auto grid max-w-6xl gap-8 px-6 py-16 md:grid-cols-3"><article><h2 className="text-xl font-semibold">Reservas online</h2><p className="mt-3 text-stone-600">Tu cliente elige profesional, paga anticipo y la cita entra confirmada.</p></article><article><h2 className="text-xl font-semibold">Control operativo</h2><p className="mt-3 text-stone-600">Ventas, compras, gastos y alertas de stock para decidir con datos.</p></article><article><h2 className="text-xl font-semibold">Equipo conectado</h2><p className="mt-3 text-stone-600">Roles, sucursales y agenda compartida sin dar acceso a información ajena.</p></article></div></section>
    <section className="mx-auto max-w-6xl px-6 py-20" id="planes"><p className="label">Planes</p><h2 className="mt-2 text-3xl font-semibold">Parte con lo que necesitas</h2><div className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-semibold">Starter</h3><p className="mt-2 text-2xl font-semibold">$19.990 <span className="text-sm font-normal">/ mes</span></p><p className="mt-4 text-sm text-stone-600">Para una sucursal y equipo pequeño.</p></article><article className="rounded-2xl bg-teal-700 p-6 text-white shadow-sm"><h3 className="font-semibold">Pro</h3><p className="mt-2 text-2xl font-semibold">$39.990 <span className="text-sm font-normal">/ mes</span></p><p className="mt-4 text-sm text-teal-50">Reservas online, recordatorios y comisiones.</p></article><article className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="font-semibold">Business</h3><p className="mt-2 text-2xl font-semibold">$69.990 <span className="text-sm font-normal">/ mes</span></p><p className="mt-4 text-sm text-stone-600">Para operación con varias sucursales.</p></article></div></section>
    <footer className="mx-auto flex max-w-6xl flex-wrap justify-between gap-3 px-6 py-8 text-sm text-stone-600"><span>Salon SaaS</span><a href="mailto:soporte@salonsaas.cl">soporte@salonsaas.cl</a></footer>
  </main>;
}